"""CLI entry point for Deal Crawler price scraper."""

from data_loader import load_products
from finder import find_cheapest_prices
from http_client import HttpClient


def main():
    """Main function to run the price scraper."""
    # Load products from YAML
    products = load_products("data.yml")

    if not products:
        print("\nNo products to compare. Exiting.")
        return

    # Find cheapest prices using HttpClient context manager
    with HttpClient() as http_client:
        results = find_cheapest_prices(products, http_client)

    # Display results as markdown
    print("\n# 🛒 Cheapest Prices\n")

    # Create markdown table
    print("| Product | Price | Link |")
    print("|---------|-------|------|")

    for product_name, result in results.items():
        if result:
            price, url = result
            # Shorten URL for display (show domain)
            from urllib.parse import urlparse
            domain = urlparse(url).netloc.replace("www.", "")
            print(f"| **{product_name}** | €{price:.2f} | [🔗 {domain}]({url}) |")
        else:
            print(f"| **{product_name}** | _No prices found_ | - |")

    print("\n---\n")
    print("_Generated by [Deal Crawler](https://github.com/vilaca/deal-crawler)_")


if __name__ == "__main__":
    main()
