Avène Couvrance Fluido Maquiagem:
  - https://farmacentral.pt/pt/artigo/avene-couvrance-base-fluida-areia-30ml
  - https://wells.pt/couvrance-fluid-foundation-corrector-3.0-3599509.html
  - https://www.atida.com/pt-pt/avene-couvrance-fluido-areia-spf20-30ml
  - https://www.farmacia365.pt/avene-couvrance-base-fluido-areia-30ml_6600163
  - https://www.farmacia365.pt/avene-couvrance-base-fluido-bege-30ml_6951863
  - https://www.notino.pt/avene/couvrance-base-de-cobertura-liquida-spf-20/p-11635778/
  - https://www.notino.pt/avene/couvrance-base-de-cobertura-liquida-spf-20/p-15685198/
# Cerave Foaming Cleanser (1000ml):
#   - https://aveirofarma.pt/cerave-gel-espuma-de-limpeza-1000ml
#   - https://wells.pt/foaming-cleanser-normal-to-oily-skin-6703197.html
#   - https://www.atida.com/pt-pt/cerave-gel-limpador-espumoso-1-litro
# Cerave Foaming Cleanser (236ml):
#   - https://aveirofarma.pt/cerave-gel-espuma-de-limpeza-236ml
#   - https://wells.pt/gel-limpeza-rosto-e-corpo-espuma-6616330.html
#   - https://www.atida.com/pt-pt/cerave-gel-limpador-espumoso-236ml
#   - https://www.blinkshop.com/cerave-foaming-cleanser-normal-to-oily-skin-236ml
# Cerave Foaming Cleanser (2x1000ml):
#   - https://www.atida.com/pt-pt/cerave-gel-de-limpeza-espumoso-2x1-litro
# Cerave Foaming Cleanser (2x473ml):
#   - https://www.atida.com/pt-pt/cerave-espuma-de-limpeza-473-ml-recarga
#   - https://www.atida.com/pt-pt/cerave-gel-de-limpeza-espumoso-2x473-ml
# Cerave Foaming Cleanser (473ml):
#   - https://aveirofarma.pt/cerave-gel-espuma-de-limpeza-473ml
#   - https://aveirofarma.pt/cerave-gel-espuma-de-limpeza-recarga-473ml
#   - https://skin.pt/cerave-foaming-cleanser-gel-espuma-de-limpeza-purificante?opt=473ml&attr=uom
#   - https://wells.pt/gel-limpeza-rosto-e-corpo-espuma-6616332.html
#   - https://www.atida.com/pt-pt/cerave-gel-limpador-espumoso-473ml
#   - https://www.atida.com/pt-pt/cerave-refil-espuma-de-limpeza-473-ml
#   - https://www.blinkshop.com/cerave-gel-espuma-de-limpeza-pele-sensvel-normal-a-oleosa-473ml
Cerave Hydrating Cleanser (1000ml):
  - https://aveirofarma.pt/cerave-creme-hidratante-de-limpeza-1000ml-
  - https://wells.pt/creme-limpeza-rosto-e-corpo-hidratante-6703201.html
  - https://www.atida.com/pt-pt/cerave-de-limpeza-hidratante-1-litro
  - https://www.farmacia365.pt/cerave-creme-limpeza-hidratante-rostocorpo-1000ml
Cerave Hydrating Cleanser (236ml):
  - https://aveirofarma.pt/cerave-creme-hidratante-de-limpeza-236ml
  - https://farmacentral.pt/pt/artigo/cerave-cleanser-hydrating-limpeza-facial-236ml
  - https://www.atida.com/pt-pt/cerave-limpador-hidratante-236ml
  - https://www.blinkshop.com/cerave-creme-de-limpeza-facial-hidratante-pele-sensvel-normal-a-seca-236ml
  - https://www.farmacia365.pt/cerave-creme-limpeza-hidratante-236ml
  - https://www.notino.pt/cerave/cleansers-emulsao-de-limpeza-com-efeito-hidratante/p-15692605/
Cerave Hydrating Cleanser (2x1000ml):
  - https://www.atida.com/pt-pt/cerave-creme-de-limpeza-hidratante-2x1-litro
Cerave Hydrating Cleanser (2x236ml):
  - https://www.atida.com/pt-pt/cerave-creme-de-limpeza-hidratante-2x236-ml
Cerave Hydrating Cleanser (2x473ml):
  - https://www.atida.com/pt-pt/cerave-creme-de-limpeza-hidratante-2x473-ml
  - https://www.atida.com/pt-pt/cerave-limpador-hidratante-473-ml-recarga
Cerave Hydrating Cleanser (473ml):
  - https://aveirofarma.pt/cerave-creme-hidratante-de-limpeza-473ml
  - https://aveirofarma.pt/cerave-creme-hidratante-de-limpeza-recarga-473ml
  - https://farmacentral.pt/pt/artigo/cerave-cleanser-hydrating-limpeza-facial-473ml
  - https://wells.pt/creme-limpeza-rosto-e-corpo-hidratante-6616328.html
  - https://www.atida.com/pt-pt/cerave-limpador-hidratante-473ml
  - https://www.atida.com/pt-pt/cerave-limpador-hidratante-recharge-473-ml
  - https://www.blinkshop.com/cerave-creme-de-limpeza-facial-hidratante-pele-sensvel-normal-a-seca-473ml
  - https://www.farmacia365.pt/cerave-creme-limpeza-hidratante-rostocorpo-473ml
  - https://www.farmacia365.pt/cerave-refill-limpeza-hidratante-473ml
  - https://www.notino.pt/cerave/cleansers-emulsao-de-limpeza-com-efeito-hidratante/p-15692412/
  - https://www.notino.pt/cerave/cleansers-emulsao-de-limpeza-com-efeito-hidratante/p-16298662/
Cerave Hydrating Cream To Foam Cleanser (236ml):
  - https://aveirofarma.pt/cerave-creme-espuma-236ml
  - https://wells.pt/hydrating-cream-to-foam-cleanser-7291595.html
  - https://www.atida.com/pt-pt/cerave-de-limpeza-creme-espuma-hidratante-236ml
  - https://www.notino.pt/cerave/cleansers-creme-espumoso-de-limpeza-para-pele-normal-a-seca/p-16066027/
Cerave Hydrating Cream To Foam Cleanser (2x236ml):
  - https://www.atida.com/pt-pt/cerave-crema-espuma-de-limpeza-hidratante-2x236-ml
Cerave Hydrating Cream To Foam Cleanser (473ml):
  - https://aveirofarma.pt/cera-ve-creme-espuma-de-limpeza-hidratante-473ml
  - https://skin.pt/cerave-hydrating-cream-to-foam-cleanser-creme-espuma-de-limpeza?attr=uom&opt=473ml
  - https://wells.pt/hydrating-cream-to-foam-cleanser-8362148.html
Cerave Micellar Water (295ml):
  - https://skin.pt/cerave-micellar-cleansing-water-agua-micelar-295ml
  - https://wells.pt/micellar-cleansing-water-6703198.html
  - https://www.atida.com/pt-pt/cerave-agua-micelar-295ml
  - https://www.farmacia365.pt/cerave-agua-micelar-295ml
Cerave Micellar Water (2x295ml):
  - https://www.atida.com/pt-pt/cerave-gua-micelar-2x295-ml
Dercos DS (200ml):
  - https://wells.pt/dercos-anti-pelicullaire-ds-shampooing-gras-285450.html#200ml
Dercos DS (390ml):
  - https://atuafarmacia.pt/products/dercos-anticaspa-ch-caspa-oleosa-390ml
  - https://wells.pt/dercos-anti-pelicullaire-ds-shampooing-gras-285450.html#390ml
# Eucerin Hyaluron-Filler Epigenetic:
#   - https://www.sabina.com/pt/cosmetica-facial-mulher/34015-hyaluron-filler-epigenetic-serum-antienvelhecimento.html
#   - https://www.farmaciacarvalho.pt/eucerin-hf-epigenetic-serum-30ml.html
#   - https://skin.pt/eucerin-hyaluron-filler-serum-epigenetic-30ml
#   - https://healtsy.pt/pt/artigo/eucerin-hf-epigenetic-serum-30ml
#   - https://easyfarma.pt/products/eucerin-hyaluron-filler-serum-epigenetic-30ml
#   - https://www.notino.pt/eucerin/hyaluron-filler-serum-rejuvenescedor-intensivo-anti-idade-de-pele/
#   - https://www.atida.com/pt-pt/eucerin-hyaluron-filler-epigenetic-soro-30-ml
#   - https://www.sweetcare.pt/pt/eucerin-hyaluron-filler-epigenetic-serum-epicelline-p-021666eu?st=01
#   - https://www.blinkshop.com/eucerin-hyaluron-filler-serum-epigenetic-30ml
#   - https://aveirofarma.pt/eucerin-hyaluron-filler-serum-epigenetico-30ml
#   - https://wells.pt/serum-rosto-epigenetic-hyaluron-filler-8090716.html
LRP Anthelios UVMune 400 SPF50:
  - https://wells.pt/protetor-solar-anthelios-uvmune-400-spf50-7577494.html
  - https://www.atida.com/pt-pt/la-roche-posay-anthelios-xl-50-creme-fondante-50ml-sem-perfume
  - https://www.farmacia365.pt/la-roche-posay-anthelios-uvmune-400-creme-s-perfume-spf50-50ml
  - https://www.notino.pt/la-roche-posay/anthelios-creme-protetor-de-dia-spf-50
LRP Anthelios UVMune 400 SPF50 - Oil control:
  - https://skin.pt/la-roche-posay-anthelios-spf50-gel-creme-toque-seco-sem-perfume-50ml
  - https://wells.pt/protetor-solar-anthelios-uvmune-400-spf50-5058410.html
  - https://www.atida.com/pt-pt/la-roche-posay-anthelios-xl-50-spf-gel-creme-toque-seco-50ml
Medik8 Crystal Retinal 3:
  - https://skin.pt/medik8-crystal-retinal-3-serum-noturno-30ml
  - https://www.atida.com/pt-pt/medik8-crystal-retinal-3-30-ml
  - https://www.farmacia365.pt/medik8-crystal-retinal-3-serum-30ml
  - https://www.notino.pt/medik8/crystal-retinal-3-serum-de-noite-rejuvenescedor-com-vitaminas-a-e-e
  - https://www.perfumeriascoqueteo.com/tratamientos-rostro/17176-22398-crystal-retinal-10-818625024529.html
  - https://www.sabina.com/pt/cosmetica-facial-mulher/19562-medik8-crystal-retinal-3-30ml.html
  - https://www.sweetcare.pt/pt/medik8-vitamina-cristal-retinal-serum-noturno-retinal-p-017631kd?st=02
Medik8 Crystal Retinal 6:
  - https://skin.pt/medik8-crystal-retinal-6-serum-noturno-30ml
  - https://www.atida.com/pt-pt/medik8-crystal-retinal-6-30-ml
  - https://www.farmacia365.pt/medik8-crystal-retinal-6-serum-30ml
  - https://www.notino.pt/medik8/crystal-retinal-6-serum-intensivo-antirrugas-com-vitaminas-a-e-e/
  - https://www.perfumeriascoqueteo.com/nicho/17177-22400-crystal-retinal-10-818625024536.html
  - https://www.sabina.com/pt/cosmetica-facial-mulher/19563-medik8-crystal-retinal-6-30ml.html
  - https://www.sweetcare.pt/pt/medik8-vitamina-cristal-retinal-serum-noturno-retinal-p-017631kd?st=03
Medik8 Duo:
  - https://www.atida.com/pt-pt/medik8-hydra-b5-intense-30-ml-advanced-night-restore-50-ml
  - https://www.farmacia365.pt/medik8-coffret-firm-favourites-serum-hidr8-b5-intense-30ml-creme-de-noite-advanced-night-restore-50ml
  - https://www.sabina.com/pt/cosmetica-facial-mulher/35249-advanced-night-restore-50-ml-hydr8-b5-intense-30ml.html
  - https://www.sweetcare.pt/pt/medik8-moisturisers-hydr8-b5-intenso-serum-hidratante-intenso-p-017682kd?st=04
Medik8 Sleep Glycolic:
  - https://www.farmacia365.pt/medik8-sleep-glycolic-creme-30ml
  - https://www.notino.pt/medik8/sleep-glycolic-peeling-enzimatico-com-acido-glicolico-para-a-noite/
  - https://www.perfumeriascoqueteo.com/nicho/17208-22464-sleep-glycolic-818625024673.html#/tamano_ml-30_ml
  - https://www.sabina.com/pt/cosmetica-facial-mulher/19590-medik8-sleep-glycolic-30ml.html
  - https://www.blinkshop.com/medik8-sleep-glycolic-peeling-noturno-esfoliante-30ml
Medik8 Super Ferrulic:
  - https://aveirofarma.pt/medik8-super-c-ferulic-serum-iluminador-30ml
  - https://skin.pt/medik8-super-c-ferulic-serum-iluminador-30ml
  - https://www.atida.com/pt-pt/medik8-super-c-ferulic-30-ml
  - https://www.blinkshop.com/medik8-super-c30-ferulic-srum-iluminador-vitamina-c-30ml
  - https://www.farmacia365.pt/medik8-super-c-ferulic-serum-30ml
  - https://www.notino.pt/medik8/super-c-ferulic-serum-antioxidante-com-vitamina-c
  - https://www.sabina.com/pt/cosmetica-facial-mulher/19591-medik8-super-c-ferulic-30-ml.html
  - https://www.sweetcare.pt/pt/medik8-vitamin-c-super-c-ferulic-serum-vitamina-c-p-017624kd?st=01
Paradontax (500ml):
  - https://wells.pt/elixir-cuidado-gengivas-7712480.html
Paradontax gums (500ml):
  - https://wells.pt/elixir-cuidado-gengivas-7009519.html
  - https://www.atida.com/pt-pt/parodontax-colutorio-complete-protection-500-ml
  - https://www.atida.com/pt-pt/parodontax-fortalece-e-protege-enxaguante-bucal-500-ml
Paradontax pasta (2x75ml):
  - https://www.farmacia365.pt/parodontax-extra-fresh-pasta-2x75ml-70-2aunidade
Paradontax pasta (75ml):
  - https://www.atida.com/pt-pt/parodontax-extra-fresh-complete-protection-75ml
Paradontax pasta gums (2x75ml):
  - https://www.atida.com/pt-pt/parodontax-pasta-de-dentes-complete-protection-gengivas-2x75-ml
Paradontax pasta gums (75ml):
  - https://farmacentral.pt/pt/artigo/parodontax-original-gengivas-pasta-dentifrica-75ml
  - https://www.atida.com/pt-pt/parodontax-fortalece-e-protege-creme-dental-75-ml
Paradontax pasta original (2x75ml):
  - https://wells.pt/pasta-de-dentes-parodontax-original-7753557.html
